[package]
name = "illium"
version.workspace = true
edition.workspace = true

[dependencies]
clap = { version = "4.6.1", features = ["derive"] }
directories = "6.0.0"
illium-client = { version = "0.1.0", path = "../illium-client" }
illium-core = { version = "0.1.0", path = "../illium-core" }
illium-ipc = { version = "0.1.0", path = "../illium-ipc" }
thiserror = "2.0.18"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net", "time"] }

[dev-dependencies]
tempfile = "3.27.0"
