"""Bind every locked package to licence bytes; no network or ambient mutation.

Registry bytes are checked against Cargo's package/file checksums. Missing
packaged notices require an explicit hash-pinned external source register.
The output inventory uses absolute paths only in temporary build evidence;
public notices are generated by audit_native.py and contain no local paths.
"""
import hashlib
import json
from pathlib import Path
import re
import sys
import tarfile
import tomllib

import release_tool


def digest(content):
    return hashlib.sha256(content).hexdigest()


def require(condition, message):
    if not condition:
        raise ValueError(message)


def notice_name(name):
    return re.fullmatch(r"(?:licen[cs]e(?:[-._].*)?|copying(?:[-._].*)?|notice(?:[-._].*)?)", name, re.IGNORECASE) is not None


def source_notices(directory, checksum=None):
    paths = sorted(path for path in directory.iterdir() if path.is_file() and notice_name(path.name))
    for subdirectory in (directory / "LICENSES", directory / "licenses"):
        if subdirectory.is_dir() and not subdirectory.is_symlink():
            paths.extend(sorted(path for path in subdirectory.iterdir() if path.is_file()))
    parts = []
    for path in paths:
        require(not path.is_symlink(), f"licence source is a link: {path.name}")
        content = path.read_bytes()
        require(0 < len(content) <= 2_000_000, f"licence source size is invalid: {path.name}")
        content.decode("utf-8")
        if checksum is not None:
            require(checksum.get("files", {}).get(path.relative_to(directory).as_posix()) == digest(content), f"registry licence checksum differs: {path.name}")
        parts.extend([f"--- {path.relative_to(directory).as_posix()} ---\n".encode(), content, b"\n"])
    return b"".join(parts)


def registry_checksum(directory, registry, item):
    # An unpacked checksum file is mutable too, and cannot authenticate its
    # own file hashes. Always derive them from the lock-bound original archive.
    archive_path = registry.parent.parent / "cache" / registry.name / f"{item['name']}-{item['version']}.crate"
    require(archive_path.is_file() and not archive_path.is_symlink(), f"registry package checksum archive missing: {item['name']}@{item['version']}")
    require(digest(archive_path.read_bytes()) == item.get("checksum"), f"registry package checksum differs: {item['name']}@{item['version']}")
    checksums = {}
    with tarfile.open(archive_path, "r:gz") as archive:
        prefix = f"{item['name']}-{item['version']}/"
        for member in archive:
            if not member.name.startswith(prefix) or not member.isfile():
                continue
            relative = member.name[len(prefix):]
            path = Path(relative)
            if relative in ("Cargo.toml", ".cargo_vcs_info.json") or (len(path.parts) == 1 and notice_name(path.name)) or (len(path.parts) == 2 and path.parts[0] in ("licenses", "LICENSES")):
                require(relative not in checksums and member.size <= 2_000_000, "unsafe duplicate or oversized crate licence member")
                source = archive.extractfile(member)
                require(source is not None, "crate licence member is unreadable")
                checksums[relative] = digest(source.read())
    return {"package": item["checksum"], "files": checksums}


def external_notice(register_path, entry):
    name = entry.get("file", "")
    relative = Path(name)
    require(name and not relative.is_absolute() and ".." not in relative.parts and "\\" not in name, "unsafe licence register path can escape source root")
    path = register_path.parent / relative
    require(not path.is_symlink() and path.is_file() and path.resolve().is_relative_to(register_path.parent.resolve()), "unsafe licence source can escape source root")
    content = path.read_bytes()
    require(0 < len(content) <= 2_000_000 and digest(content) == entry.get("sha256"), "external licence checksum differs")
    require(entry.get("source", "").startswith("https://"), "external licence source must identify reviewed HTTPS bytes")
    content.decode("utf-8")
    return content, entry["source"]


def local_packages(workspace):
    root = tomllib.loads((workspace / "Cargo.toml").read_text(encoding="utf-8"))
    packages = {}
    paths = [workspace / member / "Cargo.toml" for member in root.get("workspace", {}).get("members", [])]
    for value in root.get("patch", {}).get("crates-io", {}).values():
        if isinstance(value, dict) and "path" in value:
            paths.append(workspace / value["path"] / "Cargo.toml")
    seen = set()
    while paths:
        path = paths.pop().resolve()
        require(path.is_relative_to(workspace.resolve()), "local package path escapes workspace")
        if path in seen:
            continue
        seen.add(path)
        if not path.is_file():
            continue
        manifest = tomllib.loads(path.read_text(encoding="utf-8"))
        sections = [manifest]
        sections.extend(manifest.get("target", {}).values())
        for section in sections:
            for kind in ("dependencies", "dev-dependencies", "build-dependencies"):
                for dependency in section.get(kind, {}).values():
                    if isinstance(dependency, dict) and "path" in dependency:
                        paths.append(path.parent / dependency["path"] / "Cargo.toml")
        package = manifest.get("package", {})
        version = package.get("version")
        if isinstance(version, dict) and version.get("workspace"):
            version = root["workspace"]["package"]["version"]
        license_value = package.get("license")
        if isinstance(license_value, dict) and license_value.get("workspace"):
            license_value = root["workspace"]["package"].get("license")
        packages[(package.get("name"), version)] = (path.parent, license_value)
    return packages


def build_inventory(workspace, registry, register_path, output_directory):
    workspace, registry = Path(workspace).resolve(), Path(registry).resolve()
    output_directory = Path(output_directory)
    require(not output_directory.exists() and not output_directory.is_symlink(), "licence evidence output must be a new owned directory")
    lock_bytes = (workspace / "Cargo.lock").read_bytes()
    lock = tomllib.loads(lock_bytes.decode())
    register = json.loads(Path(register_path).read_text(encoding="utf-8")) if register_path else {"schema": 1, "packages": {}}
    require(register.get("schema") == 1 and isinstance(register.get("packages"), dict), "invalid external licence register")
    local = local_packages(workspace)
    packages, notices = [], {}
    identities = set()
    for item in lock.get("package", []):
        name, version = item["name"], item["version"]
        source = item.get("source", "workspace-or-vendored")
        identity = name, version, source
        require(identity not in identities, "duplicate locked package identity")
        identities.add(identity)
        if source.startswith("registry+"):
            directory = registry / f"{name}-{version}"
            require(directory.is_dir() and not directory.is_symlink(), f"registry source is missing: {name}@{version}")
            checksum = registry_checksum(directory, registry, item)
            metadata_path = directory / "Cargo.toml"
            require(not metadata_path.is_symlink() and checksum.get("files", {}).get("Cargo.toml") == digest(metadata_path.read_bytes()), f"registry metadata checksum differs: {name}@{version}")
            metadata = tomllib.loads(metadata_path.read_text(encoding="utf-8"))["package"]
            require(metadata.get("name") == name and metadata.get("version") == version, "registry metadata identity differs from lock")
            license_value = metadata.get("license")
            content = source_notices(directory, checksum)
            licence_source = f"https://crates.io/api/v1/crates/{name}/{version}/download (Cargo.lock SHA-256 {item['checksum']})"
        else:
            require(source == "workspace-or-vendored" and (name, version) in local, f"unsupported licence source: {name}@{version}")
            directory, license_value = local[(name, version)]
            content = source_notices(directory)
            if not content and directory.parent == workspace:
                content = source_notices(workspace)
            licence_source = "https://github.com/arthurwolf/ilium (candidate workspace/vendor source)"
        entry = register["packages"].get(f"{name}@{version}")
        if entry:
            extra, external_source = external_notice(Path(register_path), entry)
            content = content + b"\n" + extra if content else extra
            licence_source += "; " + external_source
        require(isinstance(license_value, str) and license_value.strip() and content.strip(), f"licence bytes or declaration missing: {name}@{version}")
        hash_value = digest(content)
        notices[hash_value] = content
        packages.append({"name": name, "version": version, "source": source, "reviewed": True, "license": license_value, "license_source": licence_source, "license_file": str(output_directory.resolve() / f"{hash_value}.txt"), "license_sha256": hash_value})
    require(packages, "licence inventory cannot be empty")
    # Nothing is written until every package has complete, checksum-bound bytes.
    output_directory.mkdir(parents=True, mode=0o700)
    for hash_value, content in notices.items():
        with (output_directory / f"{hash_value}.txt").open("xb") as output:
            output.write(content)
    return {"schema": 1, "state": "reviewed", "lock_sha256": digest(lock_bytes), "reviewed_by": "checksum-bound locked source and explicit upstream notice register", "packages": packages}


def main(argv=None):
    parser = release_tool.JsonArgumentParser(description=__doc__, allow_abbrev=False)
    parser.add_argument("--workspace", type=Path, required=True)
    parser.add_argument("--registry-source", type=Path, required=True)
    parser.add_argument("--source-register", type=Path)
    parser.add_argument("--notice-directory", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    try:
        args = parser.parse_args(argv)
        require(not args.output.exists() and not args.output.is_symlink(), "licence inventory output already exists")
        inventory = build_inventory(args.workspace, args.registry_source, args.source_register, args.notice_directory)
        with args.output.open("x", encoding="utf-8") as output:
            output.write(json.dumps(inventory, indent=2) + "\n")
        print(json.dumps({"type": "artifact", "path": str(args.output.resolve()), "sha256": digest(args.output.read_bytes()), "packages": len(inventory["packages"])}))
        return 0
    except (OSError, ValueError, KeyError, TypeError, tarfile.TarError) as error:
        print(json.dumps({"type": "error", "error": str(error)}))
        return 2


if __name__ == "__main__":
    sys.exit(main())
