[package]
name = "ilium-prompts"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
handlebars = "6.3.2"
serde = "1.0.228"
serde_json = "1.0.149"
thiserror = "2.0.18"

[build-dependencies]
handlebars = "6.3.2"

[dev-dependencies]
sha2 = "0.10.9"
