//! Exact initially reachable Java26.3 surface flora/attachment vocabulary.
//! Source: surface-flora-review-001/contract-001/plant-render-requirements.json.
//! Membership is not a placement chance, native default-state proof, or art proof.
#[derive(Clone, Copy, Debug)]
pub struct FloraEntry {
    pub id: &'static str,
    pub generation_biomes: &'static [&'static str],
    pub attachment: bool,
}
pub const ENTRIES: [FloraEntry; 53] = [
    FloraEntry {
        id: "minecraft:allium",
        generation_biomes: &["minecraft:flower_forest", "minecraft:meadow"],
        attachment: false,
    },
    FloraEntry {
        id: "minecraft:azure_bluet",
        generation_biomes: &[
            "minecraft:flower_forest",
            "minecraft:meadow",
            "minecraft:plains",
            "minecraft:sunflower_plains",
        ],
        attachment: false,
    },
    FloraEntry {
        id: "minecraft:bamboo",
        generation_biomes: &["minecraft:bamboo_jungle", "minecraft:jungle"],
        attachment: false,
    },
    FloraEntry {
        id: "minecraft:bee_nest",
        generation_biomes: &[
            "minecraft:birch_forest",
            "minecraft:cherry_grove",
            "minecraft:flower_forest",
            "minecraft:forest",
            "minecraft:mangrove_swamp",
            "minecraft:meadow",
            "minecraft:old_growth_birch_forest",
            "minecraft:plains",
            "minecraft:sunflower_plains",
        ],
        attachment: true,
    },
    FloraEntry {
        id: "minecraft:blue_orchid",
        generation_biomes: &["minecraft:swamp"],
        attachment: false,
    },
    FloraEntry {
        id: "minecraft:brown_mushroom",
        generation_biomes: &[
            "minecraft:badlands",
            "minecraft:bamboo_jungle",
            "minecraft:beach",
            "minecraft:birch_forest",
            "minecraft:dappled_forest",
            "minecraft:dark_forest",
            "minecraft:desert",
            "minecraft:eroded_badlands",
            "minecraft:flower_forest",
            "minecraft:forest",
            "minecraft:frozen_river",
            "minecraft:ice_spikes",
            "minecraft:jungle",
            "minecraft:mushroom_fields",
            "minecraft:old_growth_birch_forest",
            "minecraft:old_growth_pine_taiga",
            "minecraft:old_growth_spruce_taiga",
            "minecraft:plains",
            "minecraft:river",
            "minecraft:savanna",
            "minecraft:savanna_plateau",
            "minecraft:snowy_beach",
            "minecraft:snowy_plains",
            "minecraft:snowy_taiga",
            "minecraft:sparse_jungle",
            "minecraft:stony_shore",
            "minecraft:sunflower_plains",
            "minecraft:swamp",
            "minecraft:taiga",
            "minecraft:windswept_forest",
            "minecraft:windswept_gravelly_hills",
            "minecraft:windswept_hills",
            "minecraft:windswept_savanna",
            "minecraft:wooded_badlands",
        ],
        attachment: false,
    },
    FloraEntry {
        id: "minecraft:brown_mushroom_block",
        generation_biomes: &["minecraft:dark_forest", "minecraft:mushroom_fields"],
        attachment: false,
    },
    FloraEntry {
        id: "minecraft:bush",
        generation_biomes: &[
            "minecraft:birch_forest",
            "minecraft:forest",
            "minecraft:frozen_river",
            "minecraft:old_growth_birch_forest",
            "minecraft:plains",
            "minecraft:river",
            "minecraft:windswept_forest",
            "minecraft:windswept_gravelly_hills",
            "minecraft:windswept_hills",
        ],
        attachment: false,
    },
    FloraEntry {
        id: "minecraft:cactus",
        generation_biomes: &[
            "minecraft:badlands",
            "minecraft:desert",
            "minecraft:eroded_badlands",
            "minecraft:wooded_badlands",
        ],
        attachment: false,
    },
    FloraEntry {
        id: "minecraft:cactus_flower",
        generation_biomes: &[
            "minecraft:badlands",
            "minecraft:desert",
            "minecraft:eroded_badlands",
            "minecraft:wooded_badlands",
        ],
        attachment: false,
    },
    FloraEntry {
        id: "minecraft:closed_eyeblossom",
        generation_biomes: &["minecraft:pale_garden"],
        attachment: false,
    },
    FloraEntry {
        id: "minecraft:cocoa",
        generation_biomes: &["minecraft:jungle", "minecraft:sparse_jungle"],
        attachment: true,
    },
    FloraEntry {
        id: "minecraft:cornflower",
        generation_biomes: &[
            "minecraft:flower_forest",
            "minecraft:meadow",
            "minecraft:plains",
            "minecraft:sunflower_plains",
        ],
        attachment: false,
    },
    FloraEntry {
        id: "minecraft:creaking_heart",
        generation_biomes: &["minecraft:pale_garden"],
        attachment: true,
    },
    FloraEntry {
        id: "minecraft:dandelion",
        generation_biomes: &[
            "minecraft:bamboo_jungle",
            "minecraft:beach",
            "minecraft:birch_forest",
            "minecraft:dark_forest",
            "minecraft:desert",
            "minecraft:flower_forest",
            "minecraft:forest",
            "minecraft:frozen_river",
            "minecraft:ice_spikes",
            "minecraft:jungle",
            "minecraft:meadow",
            "minecraft:old_growth_birch_forest",
            "minecraft:old_growth_pine_taiga",
            "minecraft:old_growth_spruce_taiga",
            "minecraft:plains",
            "minecraft:river",
            "minecraft:savanna",
            "minecraft:savanna_plateau",
            "minecraft:snowy_beach",
            "minecraft:snowy_plains",
            "minecraft:snowy_taiga",
            "minecraft:sparse_jungle",
            "minecraft:stony_shore",
            "minecraft:sunflower_plains",
            "minecraft:taiga",
            "minecraft:windswept_forest",
            "minecraft:windswept_gravelly_hills",
            "minecraft:windswept_hills",
            "minecraft:windswept_savanna",
        ],
        attachment: false,
    },
    FloraEntry {
        id: "minecraft:dead_bush",
        generation_biomes: &[
            "minecraft:badlands",
            "minecraft:desert",
            "minecraft:eroded_badlands",
            "minecraft:mangrove_swamp",
            "minecraft:old_growth_pine_taiga",
            "minecraft:old_growth_spruce_taiga",
            "minecraft:swamp",
            "minecraft:wooded_badlands",
        ],
        attachment: false,
    },
    FloraEntry {
        id: "minecraft:fern",
        generation_biomes: &[
            "minecraft:bamboo_jungle",
            "minecraft:jungle",
            "minecraft:old_growth_pine_taiga",
            "minecraft:old_growth_spruce_taiga",
            "minecraft:snowy_taiga",
            "minecraft:sparse_jungle",
            "minecraft:taiga",
        ],
        attachment: false,
    },
    FloraEntry {
        id: "minecraft:firefly_bush",
        generation_biomes: &[
            "minecraft:badlands",
            "minecraft:bamboo_jungle",
            "minecraft:beach",
            "minecraft:birch_forest",
            "minecraft:dark_forest",
            "minecraft:eroded_badlands",
            "minecraft:flower_forest",
            "minecraft:forest",
            "minecraft:frozen_river",
            "minecraft:ice_spikes",
            "minecraft:jungle",
            "minecraft:mangrove_swamp",
            "minecraft:mushroom_fields",
            "minecraft:old_growth_birch_forest",
            "minecraft:old_growth_pine_taiga",
            "minecraft:old_growth_spruce_taiga",
            "minecraft:pale_garden",
            "minecraft:plains",
            "minecraft:river",
            "minecraft:savanna",
            "minecraft:savanna_plateau",
            "minecraft:snowy_beach",
            "minecraft:snowy_plains",
            "minecraft:snowy_taiga",
            "minecraft:sparse_jungle",
            "minecraft:stony_shore",
            "minecraft:sunflower_plains",
            "minecraft:swamp",
            "minecraft:taiga",
            "minecraft:windswept_forest",
            "minecraft:windswept_gravelly_hills",
            "minecraft:windswept_hills",
            "minecraft:windswept_savanna",
            "minecraft:wooded_badlands",
        ],
        attachment: false,
    },
    FloraEntry {
        id: "minecraft:large_fern",
        generation_biomes: &[
            "minecraft:old_growth_pine_taiga",
            "minecraft:old_growth_spruce_taiga",
            "minecraft:snowy_taiga",
            "minecraft:taiga",
        ],
        attachment: false,
    },
    FloraEntry {
        id: "minecraft:leaf_litter",
        generation_biomes: &[
            "minecraft:dappled_forest",
            "minecraft:dark_forest",
            "minecraft:forest",
            "minecraft:wooded_badlands",
        ],
        attachment: false,
    },
    FloraEntry {
        id: "minecraft:lilac",
        generation_biomes: &[
            "minecraft:birch_forest",
            "minecraft:dark_forest",
            "minecraft:flower_forest",
            "minecraft:forest",
            "minecraft:old_growth_birch_forest",
        ],
        attachment: false,
    },
    FloraEntry {
        id: "minecraft:lily_of_the_valley",
        generation_biomes: &[
            "minecraft:birch_forest",
            "minecraft:dark_forest",
            "minecraft:flower_forest",
            "minecraft:forest",
            "minecraft:old_growth_birch_forest",
        ],
        attachment: false,
    },
    FloraEntry {
        id: "minecraft:lily_pad",
        generation_biomes: &["minecraft:mangrove_swamp", "minecraft:swamp"],
        attachment: false,
    },
    FloraEntry {
        id: "minecraft:mangrove_propagule",
        generation_biomes: &["minecraft:mangrove_swamp"],
        attachment: false,
    },
    FloraEntry {
        id: "minecraft:melon",
        generation_biomes: &[
            "minecraft:bamboo_jungle",
            "minecraft:jungle",
            "minecraft:sparse_jungle",
        ],
        attachment: false,
    },
    FloraEntry {
        id: "minecraft:moss_carpet",
        generation_biomes: &["minecraft:mangrove_swamp"],
        attachment: false,
    },
    FloraEntry {
        id: "minecraft:mushroom_stem",
        generation_biomes: &["minecraft:dark_forest", "minecraft:mushroom_fields"],
        attachment: false,
    },
    FloraEntry {
        id: "minecraft:orange_tulip",
        generation_biomes: &[
            "minecraft:flower_forest",
            "minecraft:plains",
            "minecraft:sunflower_plains",
        ],
        attachment: false,
    },
    FloraEntry {
        id: "minecraft:oxeye_daisy",
        generation_biomes: &[
            "minecraft:flower_forest",
            "minecraft:meadow",
            "minecraft:plains",
            "minecraft:sunflower_plains",
        ],
        attachment: false,
    },
    FloraEntry {
        id: "minecraft:pale_hanging_moss",
        generation_biomes: &["minecraft:pale_garden"],
        attachment: true,
    },
    FloraEntry {
        id: "minecraft:pale_moss_block",
        generation_biomes: &["minecraft:pale_garden"],
        attachment: false,
    },
    FloraEntry {
        id: "minecraft:pale_moss_carpet",
        generation_biomes: &["minecraft:pale_garden"],
        attachment: false,
    },
    FloraEntry {
        id: "minecraft:peony",
        generation_biomes: &[
            "minecraft:birch_forest",
            "minecraft:dark_forest",
            "minecraft:flower_forest",
            "minecraft:forest",
            "minecraft:old_growth_birch_forest",
        ],
        attachment: false,
    },
    FloraEntry {
        id: "minecraft:pink_petals",
        generation_biomes: &["minecraft:cherry_grove"],
        attachment: false,
    },
    FloraEntry {
        id: "minecraft:pink_tulip",
        generation_biomes: &[
            "minecraft:flower_forest",
            "minecraft:plains",
            "minecraft:sunflower_plains",
        ],
        attachment: false,
    },
    FloraEntry {
        id: "minecraft:poppy",
        generation_biomes: &[
            "minecraft:bamboo_jungle",
            "minecraft:beach",
            "minecraft:birch_forest",
            "minecraft:dark_forest",
            "minecraft:desert",
            "minecraft:flower_forest",
            "minecraft:forest",
            "minecraft:frozen_river",
            "minecraft:ice_spikes",
            "minecraft:jungle",
            "minecraft:meadow",
            "minecraft:old_growth_birch_forest",
            "minecraft:old_growth_pine_taiga",
            "minecraft:old_growth_spruce_taiga",
            "minecraft:plains",
            "minecraft:river",
            "minecraft:savanna",
            "minecraft:savanna_plateau",
            "minecraft:snowy_beach",
            "minecraft:snowy_plains",
            "minecraft:snowy_taiga",
            "minecraft:sparse_jungle",
            "minecraft:stony_shore",
            "minecraft:sunflower_plains",
            "minecraft:taiga",
            "minecraft:windswept_forest",
            "minecraft:windswept_gravelly_hills",
            "minecraft:windswept_hills",
            "minecraft:windswept_savanna",
        ],
        attachment: false,
    },
    FloraEntry {
        id: "minecraft:pumpkin",
        generation_biomes: &[
            "minecraft:badlands",
            "minecraft:bamboo_jungle",
            "minecraft:beach",
            "minecraft:birch_forest",
            "minecraft:dark_forest",
            "minecraft:desert",
            "minecraft:eroded_badlands",
            "minecraft:flower_forest",
            "minecraft:forest",
            "minecraft:frozen_river",
            "minecraft:grove",
            "minecraft:ice_spikes",
            "minecraft:jungle",
            "minecraft:old_growth_birch_forest",
            "minecraft:old_growth_pine_taiga",
            "minecraft:old_growth_spruce_taiga",
            "minecraft:pale_garden",
            "minecraft:plains",
            "minecraft:river",
            "minecraft:savanna",
            "minecraft:savanna_plateau",
            "minecraft:snowy_beach",
            "minecraft:snowy_plains",
            "minecraft:snowy_slopes",
            "minecraft:snowy_taiga",
            "minecraft:sparse_jungle",
            "minecraft:stony_shore",
            "minecraft:sunflower_plains",
            "minecraft:swamp",
            "minecraft:taiga",
            "minecraft:windswept_forest",
            "minecraft:windswept_gravelly_hills",
            "minecraft:windswept_hills",
            "minecraft:windswept_savanna",
            "minecraft:wooded_badlands",
        ],
        attachment: false,
    },
    FloraEntry {
        id: "minecraft:red_mushroom",
        generation_biomes: &[
            "minecraft:badlands",
            "minecraft:bamboo_jungle",
            "minecraft:beach",
            "minecraft:birch_forest",
            "minecraft:dark_forest",
            "minecraft:desert",
            "minecraft:eroded_badlands",
            "minecraft:flower_forest",
            "minecraft:forest",
            "minecraft:frozen_river",
            "minecraft:ice_spikes",
            "minecraft:jungle",
            "minecraft:mushroom_fields",
            "minecraft:old_growth_birch_forest",
            "minecraft:old_growth_pine_taiga",
            "minecraft:old_growth_spruce_taiga",
            "minecraft:plains",
            "minecraft:river",
            "minecraft:savanna",
            "minecraft:savanna_plateau",
            "minecraft:snowy_beach",
            "minecraft:snowy_plains",
            "minecraft:snowy_taiga",
            "minecraft:sparse_jungle",
            "minecraft:stony_shore",
            "minecraft:sunflower_plains",
            "minecraft:swamp",
            "minecraft:taiga",
            "minecraft:windswept_forest",
            "minecraft:windswept_gravelly_hills",
            "minecraft:windswept_hills",
            "minecraft:windswept_savanna",
            "minecraft:wooded_badlands",
        ],
        attachment: false,
    },
    FloraEntry {
        id: "minecraft:red_mushroom_block",
        generation_biomes: &["minecraft:dark_forest", "minecraft:mushroom_fields"],
        attachment: false,
    },
    FloraEntry {
        id: "minecraft:red_shrub",
        generation_biomes: &["minecraft:dappled_forest"],
        attachment: false,
    },
    FloraEntry {
        id: "minecraft:red_tulip",
        generation_biomes: &[
            "minecraft:flower_forest",
            "minecraft:plains",
            "minecraft:sunflower_plains",
        ],
        attachment: false,
    },
    FloraEntry {
        id: "minecraft:rose_bush",
        generation_biomes: &[
            "minecraft:birch_forest",
            "minecraft:dark_forest",
            "minecraft:flower_forest",
            "minecraft:forest",
            "minecraft:old_growth_birch_forest",
        ],
        attachment: false,
    },
    FloraEntry {
        id: "minecraft:shelf_mushroom",
        generation_biomes: &["minecraft:dappled_forest"],
        attachment: true,
    },
    FloraEntry {
        id: "minecraft:short_dry_grass",
        generation_biomes: &[
            "minecraft:badlands",
            "minecraft:desert",
            "minecraft:eroded_badlands",
            "minecraft:wooded_badlands",
        ],
        attachment: false,
    },
    FloraEntry {
        id: "minecraft:short_grass",
        generation_biomes: &[
            "minecraft:badlands",
            "minecraft:bamboo_jungle",
            "minecraft:beach",
            "minecraft:birch_forest",
            "minecraft:cherry_grove",
            "minecraft:dappled_forest",
            "minecraft:dark_forest",
            "minecraft:desert",
            "minecraft:eroded_badlands",
            "minecraft:flower_forest",
            "minecraft:forest",
            "minecraft:frozen_river",
            "minecraft:ice_spikes",
            "minecraft:jungle",
            "minecraft:mangrove_swamp",
            "minecraft:meadow",
            "minecraft:old_growth_birch_forest",
            "minecraft:old_growth_pine_taiga",
            "minecraft:old_growth_spruce_taiga",
            "minecraft:pale_garden",
            "minecraft:plains",
            "minecraft:river",
            "minecraft:savanna",
            "minecraft:savanna_plateau",
            "minecraft:snowy_beach",
            "minecraft:snowy_plains",
            "minecraft:snowy_taiga",
            "minecraft:sparse_jungle",
            "minecraft:stony_shore",
            "minecraft:sunflower_plains",
            "minecraft:swamp",
            "minecraft:taiga",
            "minecraft:windswept_forest",
            "minecraft:windswept_gravelly_hills",
            "minecraft:windswept_hills",
            "minecraft:windswept_savanna",
            "minecraft:wooded_badlands",
        ],
        attachment: false,
    },
    FloraEntry {
        id: "minecraft:sugar_cane",
        generation_biomes: &[
            "minecraft:badlands",
            "minecraft:bamboo_jungle",
            "minecraft:beach",
            "minecraft:birch_forest",
            "minecraft:dark_forest",
            "minecraft:desert",
            "minecraft:eroded_badlands",
            "minecraft:flower_forest",
            "minecraft:forest",
            "minecraft:frozen_river",
            "minecraft:ice_spikes",
            "minecraft:jungle",
            "minecraft:mushroom_fields",
            "minecraft:old_growth_birch_forest",
            "minecraft:old_growth_pine_taiga",
            "minecraft:old_growth_spruce_taiga",
            "minecraft:pale_garden",
            "minecraft:plains",
            "minecraft:river",
            "minecraft:savanna",
            "minecraft:savanna_plateau",
            "minecraft:snowy_beach",
            "minecraft:snowy_plains",
            "minecraft:snowy_taiga",
            "minecraft:sparse_jungle",
            "minecraft:stony_shore",
            "minecraft:sunflower_plains",
            "minecraft:swamp",
            "minecraft:taiga",
            "minecraft:windswept_forest",
            "minecraft:windswept_gravelly_hills",
            "minecraft:windswept_hills",
            "minecraft:windswept_savanna",
            "minecraft:wooded_badlands",
        ],
        attachment: false,
    },
    FloraEntry {
        id: "minecraft:sunflower",
        generation_biomes: &["minecraft:sunflower_plains"],
        attachment: false,
    },
    FloraEntry {
        id: "minecraft:sweet_berry_bush",
        generation_biomes: &[
            "minecraft:old_growth_pine_taiga",
            "minecraft:old_growth_spruce_taiga",
            "minecraft:snowy_taiga",
            "minecraft:taiga",
        ],
        attachment: false,
    },
    FloraEntry {
        id: "minecraft:tall_dry_grass",
        generation_biomes: &[
            "minecraft:badlands",
            "minecraft:desert",
            "minecraft:eroded_badlands",
            "minecraft:wooded_badlands",
        ],
        attachment: false,
    },
    FloraEntry {
        id: "minecraft:tall_grass",
        generation_biomes: &[
            "minecraft:cherry_grove",
            "minecraft:meadow",
            "minecraft:pale_garden",
            "minecraft:plains",
            "minecraft:savanna",
            "minecraft:savanna_plateau",
            "minecraft:sunflower_plains",
        ],
        attachment: false,
    },
    FloraEntry {
        id: "minecraft:vine",
        generation_biomes: &[
            "minecraft:bamboo_jungle",
            "minecraft:dark_forest",
            "minecraft:forest",
            "minecraft:jungle",
            "minecraft:mangrove_swamp",
            "minecraft:plains",
            "minecraft:savanna",
            "minecraft:savanna_plateau",
            "minecraft:sparse_jungle",
            "minecraft:sunflower_plains",
            "minecraft:swamp",
            "minecraft:windswept_forest",
            "minecraft:windswept_gravelly_hills",
            "minecraft:windswept_hills",
            "minecraft:windswept_savanna",
            "minecraft:wooded_badlands",
        ],
        attachment: true,
    },
    FloraEntry {
        id: "minecraft:white_tulip",
        generation_biomes: &[
            "minecraft:flower_forest",
            "minecraft:plains",
            "minecraft:sunflower_plains",
        ],
        attachment: false,
    },
    FloraEntry {
        id: "minecraft:wildflowers",
        generation_biomes: &[
            "minecraft:birch_forest",
            "minecraft:meadow",
            "minecraft:old_growth_birch_forest",
        ],
        attachment: false,
    },
];
